name: main

on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    tail_and_check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Start tailing file
              run: tail -f /etc/issue >/dev/null 2>&1 &

            - name: Print processes
              run: ps aux
